baseURL = 'https://nickebbitt.com/'
languageCode = 'en-uk'
title = 'My personal site'
theme = 'terminal'
[permalinks]
  posts = '/blog/:year/:month/:day/:title/'
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4